language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: a538tPPw209p8Sce4plz1V8HEGkwvW6tU75m7s4oTU8wDGqUp9l3mvFfGHnTrppA6sYPxg++ChXFFFJ7LiqWIk4cIBWK8Z+LsWQtTzznAsL95F/iV+dojimnJg/AnXPvfdolbXAlaX6IeMm0glugQiPWbtvNekVZAJgJ8X0edn4odHO+tyF7j+6vvdCNIvDV/d/GbbFEyr9xTI7zqYXYVFCsoLuAvvn+xV2Tb43W1okm4betGMmcHcqNy4/Tx+/TQFHZeE+sUbZugs9R4OQjJwxTGYVgllXuyA1+6PZ9WcQmBcq6y3aIWO6tShUSBK8lzvLJpwElcDrwvOMQeEUeV9zRvW3LLgamibYJ/il/efEzyyCgmHVpNMDlB7t/n6571sKlSx7bfuG8vtS5IJCpaAI1aryLMPEqJl6TXeeVwi7uWhrE9M4q30IiDikrCwkvxhFtYLJJ2adSocUX272Xh6mGIlq1g0CbttuWQdoyTFn4zwN1lLj8VEeO88zlpd6nanZ55gOnzush6GmJZimHA2IB15dNuqt1me/jTIEU8ETx40DBTxiAsh+nVEYWQbJRdH8RUKTif0sblAbjMm7RkuCW1OEjWqvDBUkEbI7389vY7XUqRjrnrt/QKFRDhRu/r0vNxw+rrQWUWbwAadZRPj6ayS2KpbUdbDR18D6wV04=
  app: fast-lowlands-63508
  on:
    repo: NicolasMachado/blog-API
